### ISSUE TITLE
节点操作报错

### ISSUE THREAD

**Issue by halfss** [ruby-china/homeland-docker#37]
hello：
homeland-docker这个项目确实很规范和标准；用起来很舒服

我在使用的过程中如果对节点进行多次操作，然后在访问 /admin/nodes的时候就会出错，报错如下，可以帮忙看下吗？

```
undefined method `name' for nil:NilClass
#<ActionView::Template::Error: undefined method `name' for nil:NilClass>


--------------------------------------------------
Method:     GET
URL:        http://203.156.197.86:8081/admin/nodes
User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36
Language:   zh-CN,zh;q=0.9,en-US;q=0.8,en;q=0.7,en-GB;q=0.6,zh-TW;q=0.5,zh-HK;q=0.4
Server:     0b76a2bf5f18
Process:    9
--------------------------------------------------


/var/www/homeland/app/views/admin/nodes/index.html.erb:23:in `block in _app_views_admin_nodes_index_html_erb___653521820057188311_70040096746060'
/var/www/homeland/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.0.rc1/lib/active_record/relation/delegation.rb:41:in `each'
/var/www/homeland/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.0.rc1/lib/active_record/relation/delegation.rb:41:in `each'
/var/www/homeland/app/views/admin/nodes/index.html.erb:19:in `_app_views_admin_nodes_index_html_erb___653521820057188311_70040096746060'
/var/www/homeland/vendor/bundle/ruby/2.5.0/gems/actionview-5.2.0.rc1/lib/action_view/template.rb:159:in `block in render'
/var/www/homeland/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.0.rc1/lib/active_support/notifications.rb:170:in `instrument'
/var/www/homeland/vendor/bundle/ruby/2.5.0/gems/actionview-5.2.0.rc1/lib/action_view/template.rb:354:in `instrument_render_template'
/var/www/homeland/vendor/bundle/ruby/2.5.0/gems/actionview-5.2.0.rc1/lib/action_view/template.rb:157:in `render'
/var/www/homeland/vendor/bundle/ruby/2.5.0/gems/actionview-5.2.0.rc1/lib/action_view/renderer/template_renderer.rb:54:in `block (2 levels) in render_template'
/var/www/homeland/vendor/bundle/ruby/2.5.0/gems/actionview-5.2.0.rc1/lib/action_view/renderer/abstract_renderer.rb:44:in `block in instrument'
/var/www/homeland/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.0.rc1/lib/active_support/notifications.rb:168:in `block in instrument'
/var/www/homeland/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.0.rc1/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
/var/www/homeland/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.0.rc1/lib/active_support/notifications.rb:168:in `instrument'
/var/www/homeland/vendor/bundle/ruby/2.5.0/gems/actionview-5.2.0.rc1/lib/action_view/renderer/abstract_renderer.rb:43:in `instrument'
/var/www/homeland/vendor/bundle/ruby/2.5.0/gems/actionview-5.2.0.rc1/lib/action_view/renderer/template_renderer.rb:53:in `block in render_template'
/var/www/homeland/vendor/bundle/ruby/2.5.0/gems/actionview-5.2.0.rc1/lib/action_view/renderer/template_renderer.rb:61:in `render_with_layout'
/var/www/homeland/vendor/bundle/ruby/2.5.0/gems/actionview-5.2.0.rc1/lib/action_view/renderer/template_renderer.rb:52:in `render_template'
/var/www/homeland/vendor/bundle/ruby/2.5.0/gems/actionview-5.2.0.rc1/lib/action_view/renderer/template_renderer.rb:16:in `render'
/var/www/homeland/vendor/bundle/ruby/2.5.0/gems/actionview-5.2.0.rc1/lib/action_view/renderer/renderer.rb:44:in `render_template'
/var/www/homeland/vendor/bundle/ruby/2.5.0/gems/actionview-5.2.0.rc1/lib/action_view/renderer/renderer.rb:25:in `render'
/var/www/homeland/vendor/bundle/ruby/2.5.0/gems/actionview-5.2.0.rc1/lib/action_view/rendering.rb:103:in `_render_template'
/var/www/homeland/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.0.rc1/lib/action_controller/metal/streaming.rb:219:in `_render_template'
/var/www/homeland/vendor/bundle/ruby/2.5.0/gems/actionview-5.2.0.rc1/lib/action_view/rendering.rb:84:in `render_to_body'
/var/www/homeland/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.0.rc1/lib/action_controller/metal/rendering.rb:52:in `render_to_body'
/var/www/homeland/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.0.rc1/lib/action_controller/metal/renderers.rb:142:in `render_to_body'
/var/www/homeland/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.0.rc1/lib/abstract_controller/rendering.rb:25:in `render'
/var/www/homeland/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.0.rc1/lib/action_controller/metal/rendering.rb:36:in `render'
/var/www/homeland/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.0.rc1/lib/action_controller/metal/instrumentation.rb:46:in `block (2 levels) in render'
/var/www/homeland/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.0.rc1/lib/active_support/core_ext/benchmark.rb:14:in `block in ms'
/usr/local/lib/ruby/2.5.0/benchmark.rb:308:in `realtime'
/var/www/homeland/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.0.rc1/lib/active_support/core_ext/benchmark.rb:14:in `ms'
/var/www/homeland/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.0.rc1/lib/action_controller/metal/instrumentation.rb:46:in `block in render'
/var/www/homeland/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.0.rc1/lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
/var/www/homeland/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.0.rc1/lib/active_record/railties/controller_runtime.rb:31:in `cleanup_view_runtime'
/var/www/homeland/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.0.rc1/lib/action_controller/metal/instrumentation.rb:45:in `render'
/var/www/homeland/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.0.rc1/lib/action_controller/metal/implicit_render.rb:35:in `default_render'
/var/www/homeland/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.0.rc1/lib/action_controller/metal/basic_implicit_render.rb:6:in `block in send_action'
/var/www/homeland/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.0.rc1/lib/action_controller/metal/basic_implicit_render.rb:6:in `tap'
/var/www/homeland/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.0.rc1/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
/var/www/homeland/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.0.rc1/lib/abstract_controller/base.rb:194:in `process_action'
/var/www/homeland/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.0.rc1/lib/action_controller/metal/rendering.rb:30:in `process_action'
/var/www/homeland/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.0.rc1/lib/abstract_controller/callbacks.rb:42:in `block in process_action'
/var/www/homeland/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.0.rc1/lib/active_support/callbacks.rb:132:in `run_callbacks'
/var/www/homeland/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.0.rc1/lib/abstract_controller/callbacks.rb:41:in `process_action'
/var/www/homeland/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.0.rc1/lib/action_controller/metal/rescue.rb:22:in `process_action'
/var/www/homeland/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.0.rc1/lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
/var/www/homeland/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.0.rc1/lib/active_support/notifications.rb:168:in `block in instrument'
/var/www/homeland/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.0.rc1/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
/var/www/homeland/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.0.rc1/lib/active_support/notifications.rb:168:in `instrument'
/var/www/homeland/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.0.rc1/lib/action_controller/metal/instrumentation.rb:32:in `process_action'
/var/www/homeland/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.0.rc1/lib/action_controller/metal/params_wrapper.rb:256:in `process_action'
/var/www/homeland/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.0.rc1/lib/active_record/railties/controller_runtime.rb:24:in `process_action'
/var/www/homeland/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.0.rc1/lib/abstract_controller/base.rb:134:in `process'
/var/www/homeland/vendor/bundle/ruby/2.5.0/gems/actionview-5.2.0.rc1/lib/action_view/rendering.rb:32:in `process'
/var/www/homeland/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.0.rc1/lib/action_controller/metal.rb:191:in `dispatch'
/var/www/homeland/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.0.rc1/lib/action_controller/metal.rb:252:in `dispatch'
/var/www/homeland/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.0.rc1/lib/action_dispatch/routing/route_set.rb:52:in `dispatch'
/var/www/homeland/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.0.rc1/lib/action_dispatch/routing/route_set.rb:34:in `serve'
/var/www/homeland/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.0.rc1/lib/action_dispatch/journey/router.rb:52:in `block in serve'
/var/www/homeland/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.0.rc1/lib/action_dispatch/journey/router.rb:35:in `each'
/var/www/homeland/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.0.rc1/lib/action_dispatch/journey/router.rb:35:in `serve'
/var/www/homeland/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.0.rc1/lib/action_dispatch/routing/route_set.rb:840:in `call'
/var/www/homeland/vendor/bundle/ruby/2.5.0/gems/omniauth-1.7.1/lib/omniauth/strategy.rb:190:in `call!'
/var/www/homeland/vendor/bundle/ruby/2.5.0/gems/omniauth-1.7.1/lib/omniauth/strategy.rb:168:in `call'
/var/www/homeland/vendor/bundle/ruby/2.5.0/gems/http_accept_language-2.1.1/lib/http_accept_language/middleware.rb:14:in `call'
/var/www/homeland/vendor/bundle/ruby/2.5.0/gems/rack-attack-5.0.1/lib/rack/attack.rb:147:in `call'
/var/www/homeland/vendor/bundle/ruby/2.5.0/gems/exception_notification-4.2.2/lib/exception_notification/rack.rb:41:in `call'
/var/www/homeland/vendor/bundle/ruby/2.5.0/gems/warden-1.2.7/lib/warden/manager.rb:36:in `block in call'
/var/www/homeland/vendor/bundle/ruby/2.5.0/gems/warden-1.2.7/lib/warden/manager.rb:35:in `catch'
/var/www/homeland/vendor/bundle/ruby/2.5.0/gems/warden-1.2.7/lib/warden/manager.rb:35:in `call'
/var/www/homeland/vendor/bundle/ruby/2.5.0/gems/rack-2.0.4/lib/rack/tempfile_reaper.rb:15:in `call'
/var/www/homeland/vendor/bundle/ruby/2.5.0/gems/rack-2.0.4/lib/rack/etag.rb:25:in `call'
/var/www/homeland/vendor/bundle/ruby/2.5.0/gems/rack-2.0.4/lib/rack/conditional_get.rb:25:in `call'
/var/www/homeland/vendor/bundle/ruby/2.5.0/gems/rack-2.0.4/lib/rack/head.rb:12:in `call'
/var/www/homeland/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.0.rc1/lib/action_dispatch/http/content_security_policy.rb:18:in `call'
/var/www/homeland/vendor/bundle/ruby/2.5.0/gems/rack-2.0.4/lib/rack/session/abstract/id.rb:232:in `context'
/var/www/homeland/vendor/bundle/ruby/2.5.0/gems/rack-2.0.4/lib/rack/session/abstract/id.rb:226:in `call'
/var/www/homeland/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.0.rc1/lib/action_dispatch/middleware/cookies.rb:663:in `call'
/var/www/homeland/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.0.rc1/lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
/var/www/homeland/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.0.rc1/lib/active_support/callbacks.rb:98:in `run_callbacks'
/var/www/homeland/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.0.rc1/lib/action_dispatch/middleware/callbacks.rb:26:in `call'
/var/www/homeland/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.0.rc1/lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'
/var/www/homeland/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.0.rc1/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
/var/www/homeland/vendor/bundle/ruby/2.5.0/gems/railties-5.2.0.rc1/lib/rails/rack/logger.rb:38:in `call_app'
/var/www/homeland/vendor/bundle/ruby/2.5.0/gems/railties-5.2.0.rc1/lib/rails/rack/logger.rb:26:in `block in call'
/var/www/homeland/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.0.rc1/lib/active_support/tagged_logging.rb:71:in `block in tagged'
/var/www/homeland/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.0.rc1/lib/active_support/tagged_logging.rb:28:in `tagged'
/var/www/homeland/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.0.rc1/lib/active_support/tagged_logging.rb:71:in `tagged'
/var/www/homeland/vendor/bundle/ruby/2.5.0/gems/railties-5.2.0.rc1/lib/rails/rack/logger.rb:26:in `call'
/var/www/homeland/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.0.rc1/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
/var/www/homeland/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.0.rc1/lib/action_dispatch/middleware/request_id.rb:27:in `call'
/var/www/homeland/vendor/bundle/ruby/2.5.0/gems/rack-2.0.4/lib/rack/method_override.rb:22:in `call'
/var/www/homeland/vendor/bundle/ruby/2.5.0/gems/rack-2.0.4/lib/rack/runtime.rb:22:in `call'
/var/www/homeland/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.0.rc1/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
/var/www/homeland/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.0.rc1/lib/action_dispatch/middleware/executor.rb:14:in `call'
/var/www/homeland/vendor/bundle/ruby/2.5.0/gems/rack-2.0.4/lib/rack/sendfile.rb:111:in `call'
/var/www/homeland/vendor/bundle/ruby/2.5.0/gems/rack-cors-1.0.2/lib/rack/cors.rb:97:in `call'
/var/www/homeland/vendor/bundle/ruby/2.5.0/gems/rack-utf8_sanitizer-1.3.2/lib/rack/utf8_sanitizer.rb:19:in `call'
/var/www/homeland/vendor/bundle/ruby/2.5.0/gems/railties-5.2.0.rc1/lib/rails/engine.rb:524:in `call'
/var/www/homeland/vendor/bundle/ruby/2.5.0/gems/puma-3.10.0/lib/puma/configuration.rb:225:in `call'
/var/www/homeland/vendor/bundle/ruby/2.5.0/gems/puma-3.10.0/lib/puma/server.rb:605:in `handle_request'
/var/www/homeland/vendor/bundle/ruby/2.5.0/gems/puma-3.10.0/lib/puma/server.rb:437:in `process_client'
/var/www/homeland/vendor/bundle/ruby/2.5.0/gems/puma-3.10.0/lib/puma/server.rb:301:in `block in run'
/var/www/homeland/vendor/bundle/ruby/2.5.0/gems/puma-3.10.0/lib/puma/thread_pool.rb:120:in `block in spawn_thread'
```

**Comment by huacnlee** [comment]
看起来是有个错误的数据，需要后台容错
