### ISSUE TITLE
macOS 10.12.2 Beta 按照文档的操作步骤操作报错

### ISSUE THREAD

**Issue by zhzenghui** [ruby-china/homeland-docker#9]
docker version

`Docker version 1.12.3, build 6b644ec
`
docker-compose 
```
docker-compose version 1.8.1, build 878cff1
docker-py version: 1.10.3
CPython version: 2.7.9
OpenSSL version: OpenSSL 1.0.2h  3 May 2016
```

```
Using devise-encryptable 0.2.0
Bundle complete! 79 Gemfile dependencies, 185 gems now installed.
Bundled gems are installed into ./vendor/bundle.
could not connect to server: Connection refused
	Is the server running on host "postgresql" (172.17.0.5) and accepting
	TCP/IP connections on port 5432?
Couldn't create database for {"adapter"=>"postgresql", "encoding"=>"utf-8", "database"=>"homeland", "username"=>"postgres", "password"=>nil, "host"=>"postgresql", "pool"=>64}
rails aborted!
PG::ConnectionBad: could not connect to server: Connection refused
	Is the server running on host "postgresql" (172.17.0.5) and accepting
	TCP/IP connections on port 5432?
/var/www/homeland/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/postgresql_adapter.rb:671:in `initialize'
/var/www/homeland/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/postgresql_adapter.rb:671:in `new'
/var/www/homeland/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/postgresql_adapter.rb:671:in `connect'
/var/www/homeland/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/postgresql_adapter.rb:217:in `initialize'
/var/www/homeland/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/postgresql_adapter.rb:37:in `new'
/var/www/homeland/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/postgresql_adapter.rb:37:in `postgresql_connection'
/var/www/homeland/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:721:in `new_connection'
/var/www/homeland/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:765:in `checkout_new_connection'
/var/www/homeland/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:744:in `try_to_checkout_new_connection'
/var/www/homeland/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:705:in `acquire_connection'
/var/www/homeland/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:501:in `checkout'
/var/www/homeland/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:364:in `connection'
/var/www/homeland/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:875:in `retrieve_connection'
/var/www/homeland/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/connection_handling.rb:128:in `retrieve_connection'
/var/www/homeland/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/connection_handling.rb:91:in `connection'
/var/www/homeland/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/tasks/postgresql_database_tasks.rb:6:in `connection'
/var/www/homeland/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/tasks/postgresql_database_tasks.rb:15:in `create'
/var/www/homeland/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/tasks/database_tasks.rb:109:in `create'
/var/www/homeland/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/tasks/database_tasks.rb:129:in `block in create_current'
/var/www/homeland/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/tasks/database_tasks.rb:292:in `block in each_current_configuration'
/var/www/homeland/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/tasks/database_tasks.rb:291:in `each'
/var/www/homeland/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/tasks/database_tasks.rb:291:in `each_current_configuration'
/var/www/homeland/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/tasks/database_tasks.rb:128:in `create_current'
/var/www/homeland/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/railties/databases.rake:27:in `block (2 levels) in <top (required)>'
/var/www/homeland/vendor/bundle/ruby/2.3.0/gems/railties-5.0.0.1/lib/rails/commands/rake_proxy.rb:13:in `block in run_rake_task'
/var/www/homeland/vendor/bundle/ruby/2.3.0/gems/railties-5.0.0.1/lib/rails/commands/rake_proxy.rb:10:in `run_rake_task'
/var/www/homeland/vendor/bundle/ruby/2.3.0/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:51:in `run_command!'
/var/www/homeland/vendor/bundle/ruby/2.3.0/gems/railties-5.0.0.1/lib/rails/commands.rb:18:in `<top (required)>'
/var/www/homeland/bin/rails:9:in `require'
/var/www/homeland/bin/rails:9:in `<top (required)>'
/var/www/homeland/vendor/bundle/ruby/2.3.0/gems/spring-2.0.0/lib/spring/client/rails.rb:28:in `load'
/var/www/homeland/vendor/bundle/ruby/2.3.0/gems/spring-2.0.0/lib/spring/client/rails.rb:28:in `call'
/var/www/homeland/vendor/bundle/ruby/2.3.0/gems/spring-2.0.0/lib/spring/client/command.rb:7:in `call'
/var/www/homeland/vendor/bundle/ruby/2.3.0/gems/spring-2.0.0/lib/spring/client.rb:30:in `run'
/var/www/homeland/vendor/bundle/ruby/2.3.0/gems/spring-2.0.0/bin/spring:49:in `<top (required)>'
/var/www/homeland/vendor/bundle/ruby/2.3.0/gems/spring-2.0.0/lib/spring/binstub.rb:31:in `load'
/var/www/homeland/vendor/bundle/ruby/2.3.0/gems/spring-2.0.0/lib/spring/binstub.rb:31:in `<top (required)>'
/var/www/homeland/bin/spring:13:in `require'
/var/www/homeland/bin/spring:13:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
Tasks: TOP => db:create
(See full trace by running task with --trace)
make: *** [install] Error 1
```

**Comment by huacnlee** [comment]
你的电脑上已经启动了 PostgreSQL，你需要先停掉
